# Generated by Django 5.0.2 on 2024-03-11 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Divisions',
            },
        ),
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Priorities',
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=150)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.divisions')),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to='main.workers')),
                ('request_name', models.CharField(max_length=150)),
                ('request_description', models.TextField()),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_worker', to='main.workers')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.priorities')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.statuses')),
                ('date_completed', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
    ]
