# Generated by Django 5.0.2 on 2024-03-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='divisions',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobs',
            table=None,
        ),
        migrations.AlterModelTable(
            name='priorities',
            table=None,
        ),
        migrations.AlterModelTable(
            name='requests',
            table=None,
        ),
        migrations.AlterModelTable(
            name='statuses',
            table=None,
        ),
        migrations.AlterModelTable(
            name='workers',
            table=None,
        ),
    ]
