# Generated by Django 5.0.2 on 2024-02-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisions',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='priorities',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='divisions',
            table='Divisions',
        ),
        migrations.AlterModelTable(
            name='jobs',
            table='Jobs',
        ),
        migrations.AlterModelTable(
            name='priorities',
            table='Priorities',
        ),
        migrations.AlterModelTable(
            name='requests',
            table='Requests',
        ),
        migrations.AlterModelTable(
            name='statuses',
            table='Statuses',
        ),
        migrations.AlterModelTable(
            name='workers',
            table='Workers',
        ),
    ]
