# Generated by Django 5.0.2 on 2024-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_divisions_options_alter_jobs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='date_completed',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(),
        ),
    ]
