# Generated by Django 5.0.2 on 2024-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_divisions_table_alter_jobs_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='commentary',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requests',
            name='delete_commentary',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='requests',
            name='desired_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='requests',
            name='revision_commentary',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date_completed',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='requests',
            name='request_description',
            field=models.TextField(default=None),
        ),
    ]
