# Generated by Django 5.0.2 on 2024-02-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_requests_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='priorities',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={},
        ),
    ]
