# Generated by Django 5.0.2 on 2024-05-20 04:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_requests_responsible_alter_requests_issued_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Profile',
        ),
    ]
