# Generated by Django 5.0.2 on 2024-05-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='images/profile/default_profile.png', upload_to='images/profile/'),
        ),
    ]
