# Generated by Django 5.0.6 on 2024-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='images/profile/default_profile.png', null=True, upload_to='images/profile/'),
        ),
    ]
