# Generated by Django 5.0.2 on 2024-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='images/profile/default_profile.png', null=True, upload_to='avatars/'),
        ),
    ]
