# Generated by Django 5.0.2 on 2024-06-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_requests_attachment_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='avatars/default_profile.jpg', null=True, upload_to='avatars/'),
        ),
    ]
