# Generated by Django 5.0.2 on 2024-06-06 05:59

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='avatars/default_profile.jpg', force_format='JPEG', keep_meta=True, null=True, quality=90, scale=1, size=[200, 200], upload_to='avatars/'),
        ),
    ]
