# Generated by Django 5.0.2 on 2024-06-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='delete_commentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='revision_commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
