# Generated by Django 5.0.2 on 2024-06-06 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_requests_commentary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
