# Generated by Django 5.0.6 on 2024-06-06 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_requests_desired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
