# Generated by Django 5.0.6 on 2024-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_requests_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
