# Generated by Django 5.0.6 on 2024-06-06 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_requests_issued_by_alter_requests_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.statuses'),
        ),
    ]
