# Generated by Django 5.0.6 on 2024-06-06 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
