# Generated by Django 5.0.6 on 2024-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_requests_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='desired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
