# Generated by Django 5.0.6 on 2024-06-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_resourse_types_logpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpass',
            name='extra_info',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
