# Generated by Django 5.0.6 on 2024-06-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
