# Generated by Django 5.0.6 on 2024-06-22 14:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='desired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
