# Generated by Django 5.0.6 on 2024-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_requests_desired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='respounce_attachments',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
