# Generated by Django 5.0.6 on 2024-06-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_requests_respounce_attachments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='respounce_attachments',
            new_name='responce_attachments',
        ),
    ]
